language: node_js
node_js:
  - '4.3'
sudo: false
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - echo 'jsHint' && echo -en 'travis_fold:start:script.jsHint\\r'
  - npm run jsHint -- --failTaskOnError
  - echo -en 'travis_fold:end:script.jsHint\\r'

  - echo 'test non-webgl' && echo -en 'travis_fold:start:script.test\\r'
  - npm run test -- --exclude WebGL --browsers Electron --failTaskOnError --suppressPassed
  - echo -en 'travis_fold:end:script.test\\r'

  - echo 'makeZipFile' && echo -en 'travis_fold:start:script.makeZipFile\\r'
  - npm run clean
  - npm run makeZipFile
  - echo -en 'travis_fold:end:script.makeZipFile\\r'

  - echo 'test non-webgl release' && echo -en 'travis_fold:start:script test.release\\r'
  - npm run test -- --exclude WebGL --browsers Electron --failTaskOnError --release --suppressPassed
  - echo -en 'travis_fold:end:script test.release\\r'

  - echo 'cloc' && echo -en 'travis_fold:start:script.cloc\\r'
  - npm run cloc
  - echo -en 'travis_fold:end:script.cloc\\r'

  - echo 'delpoy' && echo -en 'travis_fold:start:script.deploy\\r'
  - if ! $TRAVIS_PULL_REQUEST ; then npm run deploy-s3 -- -b cesium-dev -d $TRAVIS_BRANCH --confirm -c 'no-cache' ; fi
  - echo -en 'travis_fold:end:script.deploy\\r'